Update ROADMAP.md
ONLYOFFICE/DocumentServer pull request #1175
Opened 2021-03-09 14:15 UTC by hellonadya

- add 6.3 roadmap

2021-03-09 14:28 UTC, ShockwaveNN approved these changes

2021-03-09 14:28 UTC, ShockwaveNN commented on ROADMAP.md
> +* Adding files to Favorites folder
I think should be note that this should be implemented on DMS side also

2021-03-09 14:28 UTC, ShockwaveNN commented
Also maybe old entres, like 6.2 should be deleted altogether from this doc
Because 6.2 for example contains "Forms tab" which was not included in final release

2021-03-10 08:23 UTC, hellonadya commented on ROADMAP.md
> +* Adding files to Favorites folder
for adding to favs? or for smt else too?

2021-03-10 08:46 UTC, ShockwaveNN requested changes

2021-03-10 08:46 UTC, ShockwaveNN commented on ROADMAP.md
> +* Adding files to Favorites folder
I think only favs

2021-03-10 09:07 UTC, hellonadya commented on ROADMAP.md
> +* Adding files to Favorites folder
added

2021-03-10 09:16 UTC, ShockwaveNN approved these changes

2021-03-10 12:51 UTC, trofim24 approved these changes

2021-03-10 12:51 UTC, merged